---
- hosts: all
  tasks:
    - name: 'Instala PHP'
      apt: 
        name: php5
        state: latest
      become: yes
    - name: 'Instala o Apache2'
      apt: 
        name: apache2
        state: latest
      become: yes
    - name: 'Instala o mod php'
      apt:
        name: libapache2-mod-php5
        state: latest
      become: yes
    - name: ''
